services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Numsey#2021"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
